ENDPOINTS = {'TrelloV1': {'actions': {'METHODS': {'PUT', 'DELETE', 'GET'},
                          'board': {'METHODS': {'GET'}},
                          'card': {'METHODS': {'GET'}},
                          'entities': {'METHODS': {'GET'}},
                          'list': {'METHODS': {'GET'}},
                          'member': {'METHODS': {'GET'}},
                          'member_creator': {'METHODS': {'GET'}},
                          'organization': {'METHODS': {'GET'}},
                          'text': {'METHODS': {'PUT'}}},
              'batch': {'METHODS': {'GET'}},
              'boards': {'METHODS': {'PUT', 'POST', 'GET'},
                         'actions': {'METHODS': {'GET'}},
                         'board_stars': {'METHODS': {'GET'}},
                         'calendar_key': {'generate': {'METHODS': {'POST'}}},
                         'cards': {'METHODS': {'GET'}},
                         'checklists': {'METHODS': {'POST', 'GET'}},
                         'closed': {'METHODS': {'PUT'}},
                         'deltas': {'METHODS': {'GET'}},
                         'desc': {'METHODS': {'PUT'}},
                         'email_key': {'generate': {'METHODS': {'POST'}}},
                         'id_organization': {'METHODS': {'PUT'}},
                         'label_names': {'blue': {'METHODS': {'PUT'}},
                                         'green': {'METHODS': {'PUT'}},
                                         'orange': {'METHODS': {'PUT'}},
                                         'purple': {'METHODS': {'PUT'}},
                                         'red': {'METHODS': {'PUT'}},
                                         'yellow': {'METHODS': {'PUT'}}},
                         'lists': {'METHODS': {'POST', 'GET'}},
                         'mark_as_viewed': {'METHODS': {'POST'}},
                         'members': {'METHODS': {'PUT', 'DELETE', 'GET'},
                                     'cards': {'METHODS': {'GET'}}},
                         'members_invited': {'METHODS': {'GET'}},
                         'memberships': {'METHODS': {'PUT', 'GET'}},
                         'my_prefs': {'METHODS': {'GET'},
                                      'email_position': {'METHODS': {'PUT'}},
                                      'id_email_list': {'METHODS': {'PUT'}},
                                      'show_list_guide': {'METHODS': {'PUT'}},
                                      'show_sidebar': {'METHODS': {'PUT'}},
                                      'show_sidebar_activity': {'METHODS': {'PUT'}},
                                      'show_sidebar_board_actions': {'METHODS': {'PUT'}},
                                      'show_sidebar_members': {'METHODS': {'PUT'}}},
                         'name': {'METHODS': {'PUT'}},
                         'organization': {'METHODS': {'GET'}},
                         'power_ups': {'METHODS': {'DELETE', 'POST'}},
                         'prefs': {'background': {'METHODS': {'PUT'}},
                                   'calendar_feed_enabled': {'METHODS': {'PUT'}},
                                   'card_aging': {'METHODS': {'PUT'}},
                                   'card_covers': {'METHODS': {'PUT'}},
                                   'comments': {'METHODS': {'PUT'}},
                                   'invitations': {'METHODS': {'PUT'}},
                                   'permission_level': {'METHODS': {'PUT'}},
                                   'self_join': {'METHODS': {'PUT'}},
                                   'voting': {'METHODS': {'PUT'}}},
                         'subscribed': {'METHODS': {'PUT'}}},
              'cards': {'METHODS': {'PUT', 'POST', 'GET', 'DELETE'},
                        'actions': {'METHODS': {'GET'},
                                    'comments': {'METHODS': {'DELETE',
                                                             'POST', 'PUT'}}},
                        'attachments': {'METHODS': {'DELETE', 'GET', 'POST'}},
                        'board': {'METHODS': {'GET'}},
                        'check_item_states': {'METHODS': {'GET'}},
                        'checklist': {'check_item': {'METHODS': {'DELETE',
                                                                 'POST',
                                                                 'PUT'},
                                                     'convert_to_card': {'METHODS': {'POST'}},
                                                     'name': {'METHODS': {'PUT'}},
                                                     'pos': {'METHODS': {'PUT'}},
                                                     'state': {'METHODS': {'PUT'}}}},
                        'checklists': {'METHODS': {'DELETE', 'POST', 'GET'}},
                        'closed': {'METHODS': {'PUT'}},
                        'desc': {'METHODS': {'PUT'}},
                        'due': {'METHODS': {'PUT'}},
                        'id_attachment_cover': {'METHODS': {'PUT'}},
                        'id_board': {'METHODS': {'PUT'}},
                        'id_list': {'METHODS': {'PUT'}},
                        'id_members': {'METHODS': {'PUT', 'POST', 'DELETE'}},
                        'labels': {'METHODS': {'PUT', 'POST', 'DELETE'}},
                        'list': {'METHODS': {'GET'}},
                        'mark_associated_notifications_read': {'METHODS': {'POST'}},
                        'members': {'METHODS': {'GET'}},
                        'members_voted': {'METHODS': {'DELETE', 'GET',
                                                      'POST'}},
                        'name': {'METHODS': {'PUT'}},
                        'pos': {'METHODS': {'PUT'}},
                        'stickers': {'METHODS': {'DELETE', 'GET', 'POST',
                                                 'PUT'}},
                        'subscribed': {'METHODS': {'PUT'}}},
              'checklists': {'METHODS': {'PUT', 'POST', 'GET', 'DELETE'},
                             'board': {'METHODS': {'GET'}},
                             'cards': {'METHODS': {'GET'}},
                             'check_items': {'METHODS': {'DELETE', 'GET',
                                                         'POST'}},
                             'id_card': {'METHODS': {'PUT'}},
                             'name': {'METHODS': {'PUT'}},
                             'pos': {'METHODS': {'PUT'}}},
              'lists': {'METHODS': {'PUT', 'POST', 'GET'},
                        'actions': {'METHODS': {'GET'}},
                        'archive_all_cards': {'METHODS': {'POST'}},
                        'board': {'METHODS': {'GET'}},
                        'cards': {'METHODS': {'POST', 'GET'}},
                        'closed': {'METHODS': {'PUT'}},
                        'id_board': {'METHODS': {'PUT'}},
                        'move_all_cards': {'METHODS': {'POST'}},
                        'name': {'METHODS': {'PUT'}},
                        'pos': {'METHODS': {'PUT'}},
                        'subscribed': {'METHODS': {'PUT'}}},
              'members': {'METHODS': {'PUT', 'GET'},
                          'actions': {'METHODS': {'GET'}},
                          'avatar': {'METHODS': {'POST'}},
                          'avatar_source': {'METHODS': {'PUT'}},
                          'bio': {'METHODS': {'PUT'}},
                          'board_backgrounds': {'METHODS': {'DELETE', 'GET',
                                                            'POST', 'PUT'}},
                          'board_stars': {'METHODS': {'DELETE', 'GET',
                                                      'POST', 'PUT'},
                                          'id_board': {'METHODS': {'PUT'}},
                                          'pos': {'METHODS': {'PUT'}}},
                          'boards': {'METHODS': {'GET'}},
                          'boards_invited': {'METHODS': {'GET'}},
                          'cards': {'METHODS': {'GET'}},
                          'custom_board_backgrounds': {'METHODS': {'DELETE',
                                                                   'GET',
                                                                   'POST',
                                                                   'PUT'}},
                          'custom_emoji': {'METHODS': {'POST', 'GET'}},
                          'custom_stickers': {'METHODS': {'DELETE', 'GET',
                                                          'POST'}},
                          'deltas': {'METHODS': {'GET'}},
                          'full_name': {'METHODS': {'PUT'}},
                          'id_boards_pinned': {'METHODS': {'DELETE', 'POST'}},
                          'initials': {'METHODS': {'PUT'}},
                          'notifications': {'METHODS': {'GET'}},
                          'one_time_messages_dismissed': {'METHODS': {'POST'}},
                          'organizations': {'METHODS': {'GET'}},
                          'organizations_invited': {'METHODS': {'GET'}},
                          'prefs': {'color_blind': {'METHODS': {'PUT'}},
                                    'minutes_between_summaries': {'METHODS': {'PUT'}}},
                          'saved_searches': {'METHODS': {'DELETE', 'GET',
                                                         'POST', 'PUT'},
                                             'name': {'METHODS': {'PUT'}},
                                             'pos': {'METHODS': {'PUT'}},
                                             'query': {'METHODS': {'PUT'}}},
                          'tokens': {'METHODS': {'GET'}},
                          'unpaid_account': {'METHODS': {'POST'}},
                          'username': {'METHODS': {'PUT'}}},
              'notifications': {'METHODS': {'PUT', 'GET'},
                                'all': {'read': {'METHODS': {'POST'}}},
                                'board': {'METHODS': {'GET'}},
                                'card': {'METHODS': {'GET'}},
                                'entities': {'METHODS': {'GET'}},
                                'list': {'METHODS': {'GET'}},
                                'member': {'METHODS': {'GET'}},
                                'member_creator': {'METHODS': {'GET'}},
                                'organization': {'METHODS': {'GET'}},
                                'unread': {'METHODS': {'PUT'}}},
              'organizations': {'METHODS': {'PUT', 'POST', 'GET', 'DELETE'},
                                'actions': {'METHODS': {'GET'}},
                                'boards': {'METHODS': {'GET'}},
                                'deltas': {'METHODS': {'GET'}},
                                'desc': {'METHODS': {'PUT'}},
                                'display_name': {'METHODS': {'PUT'}},
                                'logo': {'METHODS': {'DELETE', 'POST'}},
                                'members': {'METHODS': {'DELETE', 'GET',
                                                        'PUT'},
                                            'all': {'METHODS': {'DELETE'}},
                                            'cards': {'METHODS': {'GET'}},
                                            'deactivated': {'METHODS': {'PUT'}}},
                                'members_invited': {'METHODS': {'GET'}},
                                'memberships': {'METHODS': {'PUT', 'GET'}},
                                'name': {'METHODS': {'PUT'}},
                                'prefs': {'associated_domain': {'METHODS': {'DELETE',
                                                                            'PUT'}},
                                          'board_visibility_restrict': {'org': {'METHODS': {'PUT'}},
                                                                        'private': {'METHODS': {'PUT'}},
                                                                        'public': {'METHODS': {'PUT'}}},
                                          'external_members_disabled': {'METHODS': {'PUT'}},
                                          'org_invite_restrict': {'METHODS': {'DELETE',
                                                                              'PUT'}},
                                          'permission_level': {'METHODS': {'PUT'}}},
                                'unpaid_account': {'METHODS': {'POST'}},
                                'website': {'METHODS': {'PUT'}}},
              'search': {'METHODS': {'GET'}, 'members': {'METHODS': {'GET'}}},
              'sessions': {'METHODS': {'PUT', 'POST'},
                           'socket': {'METHODS': {'GET'}},
                           'status': {'METHODS': {'PUT'}}},
              'tokens': {'METHODS': {'DELETE', 'GET'},
                         'member': {'METHODS': {'GET'}},
                         'webhooks': {'METHODS': {'DELETE', 'GET', 'POST',
                                                  'PUT'}}},
              'types': {'METHODS': {'GET'}},
              'webhooks': {'METHODS': {'PUT', 'POST', 'GET', 'DELETE'},
                           'active': {'METHODS': {'PUT'}},
                           'callback_u_r_l': {'METHODS': {'PUT'}},
                           'description': {'METHODS': {'PUT'}},
                           'id_model': {'METHODS': {'PUT'}}}}}
